# Generated by Django 5.1.7 on 2025-05-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса гаманця'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_initials',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ініціали гаманця'),
        ),
    ]
