# Generated by Django 5.1.7 on 2025-05-17 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_rename_text_forumcomment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.forumtopic'),
        ),
    ]
