# Generated by Django 5.1.7 on 2025-05-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_alter_forumcomment_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='explore.forumtopic'),
        ),
    ]
