# Generated by Django 5.1.7 on 2025-05-17 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_alter_forumcomment_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='explore.forumcomment'),
        ),
    ]
