# Generated by Django 5.1.7 on 2025-05-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0008_cryptotoken_sparkline_7d'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptotoken',
            options={'ordering': ['-market_cap']},
        ),
        migrations.AddField(
            model_name='cryptotoken',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
