# Generated by Django 5.1.7 on 2025-05-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0009_alter_cryptotoken_options_cryptotoken_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptotoken',
            options={},
        ),
        migrations.RemoveField(
            model_name='cryptotoken',
            name='sparkline_7d',
        ),
        migrations.AddField(
            model_name='cryptotoken',
            name='coingecko_id',
            field=models.CharField(default='bitcoin', max_length=50),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='market_cap',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='percent_1h',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='percent_24h',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='percent_7d',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='volume_24h',
            field=models.BigIntegerField(),
        ),
    ]
