# Generated by Django 5.1.7 on 2025-05-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0010_alter_cryptotoken_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptotoken',
            name='coingecko_id',
        ),
        migrations.RemoveField(
            model_name='cryptotoken',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='cryptotoken',
            name='sparkline_7d',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='percent_1h',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='percent_24h',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='percent_7d',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='volume_24h',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
