# Generated by Django 5.1.7 on 2025-05-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0011_remove_cryptotoken_coingecko_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptotoken',
            options={'ordering': ['-market_cap']},
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
